[workspace]
resolver = "2"
default-members = ["crates/utilities"]
members = ["crates/*"]

[workspace.package]
edition = "2021"
version = "0.1.0"

[workspace.dependencies]
itertools = "0.13.0"
maplit = "1.0.2"
reqwest = "0.12.9"
tokio = "1"
